### ISSUE TITLE
problem when calling wrap function with same key multi times in the same time

### ISSUE THREAD

**Issue by tiant167** [BryanDonovan/node-cache-manager#100]
Hi,
We met a problem when calling `wrap` function with same key multi times in the same time.

We use node-cache-manager-redis-store as store engine. The `get` function of this engine will return plain object after `JSON.parse()`. I read the code in `callback_filler.js`, and found that all callbacks for same key will get the same value.

```javascript
waiting.forEach(function(task) {
  (task.cb)(err, data);
});
```

If I changed the object in the first callback function, the value will also be changed in the second callback. (I know it is not graceful to change the value of parameter)

So, should the `wrap` function return a cloned value for different caller if the value if object?

Thanks~

**Comment by BryanDonovan** [comment]
I don't think we should clone the value.. seems like that would add unnecessary overhead and other potential issues.  I think modifying the value by definition means you should expire that cache entry (which I know isn't feasible if you're making multiple simultaneous requests).  

I think you should probably do the cloning right before modifying the object.

**Comment by tiant167** [comment]
👌 Thanks~

**Comment by deyhle** [comment]
This problem seems to always exist, also when using the in-memory cache:

```js
const cache = cacheManager.caching({ store: 'memory' });
return cache.set('key', { pay: 'load1' })
.then(() => cache.get('key'))
.then((result) => {
  result.pay = 'load2';
  return cache.get('key');
})
.then((result) => {
  // the result is now { pay: 'load2' }
})
```

I would expect the cached values not to change unless "set" is called (kind of like a database works). 
I agree that the current behaviour is a design decision, but in that case it should definitely be described explicitly in the documentation.

**Comment by nitzanav** [comment]
I think that it would be good to "freeze" the output of memory cache

**Comment by BryanDonovan** [comment]
Yes, the user should freeze the object if they intend to modify it.  This is true whether you get data from cache or from a database, or just create an object yourself.

**Comment by ankopainting** [comment]
I just wanted to note that we ran into this too.  From our point of view it's a reasonable assumption that a cache like any data store will deserialise the content and it will be a copy, rather than a reference to the original.

In our case it varied between the backends - in redis it was deserialised and "copied", and in memory it was a reference.  So it's inconsistent between implementations.  So now we've got a wrapper (facade pattern) to handle this, but as far as I can tell it's not documented and it's a big gotcha.  At least if the library did a freeze people would be alerted of this problem, with minimal overhead.

**Comment by BryanDonovan** [comment]
FWIW, this was "fixed" in https://github.com/BryanDonovan/node-cache-manager/pull/103#issuecomment-580070440

.. but that led to other issues:
- https://github.com/BryanDonovan/node-cache-manager/issues/132
- https://github.com/BryanDonovan/node-cache-manager/issues/134

I'm going to look into a solution, which I think is to make the cloning optional, as soon as I have time.

**Comment by BryanDonovan** [comment]
FYI, this is hopefully fixed in https://github.com/BryanDonovan/node-cache-manager/pull/135

I haven't merged that yet.
