### ISSUE TITLE
This domain module is pending deprecation

### ISSUE THREAD

**Issue by jkernech** [BryanDonovan/node-cache-manager#38]
The errors are handled via `domain` and the module is deprecated `Stability: 0 - Deprecated` : https://nodejs.org/api/domain.html

It should be replaced with a listener :
```js
process.on('uncaughtException', function (err) {
  console.log(err.stack);
})
```

**Comment by BryanDonovan** [comment]
Cool.  I'll remove when I get some time (unless someone else wants to submit a pull request with the changes).

**Comment by jkernech** [comment]
:+1:

**Comment by zlokomatic** [comment]
I would also like to see this fixed

**Comment by BryanDonovan** [comment]
@jkernech - sorry, I didn't see your message until now.  If someone else wants to do a pull request, that would be great.  Otherwise it might be a couple weeks before I can get to this.

**Comment by BryanDonovan** [comment]
@jkernech, @zlokomatic - can you please check out https://github.com/BryanDonovan/node-cache-manager/pull/44 and let me know what you think?

This will probably require bumping the version to 2.0.0 since some people might be relying on `domain` catching the errors and passing them back in the callbacks.

**Comment by zlokomatic** [comment]
Looks good :thumbsup:
