### ISSUE TITLE
ttl of zero

### ISSUE THREAD

**Issue by Janpot** [BryanDonovan/node-cache-manager#43]
I'm trying to set a `ttl` of `0` but it seems like my objects are cached indefinitely. I'm doing this because caching time in my system is variable depending on which key (can be `0` sometimes) but I still want to benefit from the concurrency behaviour of this module all of the time, like when two calls to the same key are made at the same time.

```
var cacheManager = require('cache-manager').caching({ ttl: 0 });

function test () {
    console.log('trying cache')
    
    return cacheManager.wrap('key', function () {
        console.log('fetched')
        return Promise.resolve('value')
    }, { ttl: 0 });
    
}

test();

setTimeout(function () {
    test();    
}, 1000);
```

I would expect

```
trying cache
fetched
trying cache
fetched
```

but instead I get 

```
trying cache
fetched
trying cache
```

**Comment by BryanDonovan** [comment]
This appears to be how the underlying `lru-cache` module works.  This line in particular checks if a cached item is stale: https://github.com/isaacs/node-lru-cache/blob/master/lib/lru-cache.js#L422

.. it sees that the `maxAge` (the `ttl`) is `0` and returns `false`.  I'm not sure if this is intentional or not.

**Comment by BryanDonovan** [comment]
p.s., I upgraded `node-cache-manager` to use the latest `lru-cache` in version 1.4.0.  Older versions of `lru-cache` behaved the same way.

I also updated this line in the memory store:
https://github.com/BryanDonovan/node-cache-manager/commit/ec114bcb746b8d34c05374b8beafd23eec1ff2d2#diff-774c96972f8630e6e67be1ca15041a00R10

.. it wasn't passing the `0` `ttl` to `lru-cache`.  This wasn't affecting you since you were passing the `ttl` in the wrap function, which was correctly getting passed to `lru-cache` here: https://github.com/BryanDonovan/node-cache-manager/blob/master/lib/stores/memory.js#L25

**Comment by simlu** [comment]
Just to clarify, the current behavior for 0 is now to not cache, correct? Can this be documented please?

**Comment by BryanDonovan** [comment]
@simlu - The problem is that it's not an issue with `node-cache-manager`, it's just how `lru-cache` works.

**Comment by simlu** [comment]
So passing "0" actually never expires then? I'm ok with either behaviour. Just would prefer if it was documented

**Comment by BryanDonovan** [comment]
I'm not 100% sure actually.  You'd have to test how it works with whatever cache store you're using.  `node-cache-manager` works with three different redis libraries, two mongo libraries, lru-cache, three file system caches, a hazelcast store, memcache store, and a memory store.  I unfortunately can't document how they all work.  `node-cache-manager` simply passes the `0` to the underlying store (or at least that's what it's supposed to do; if not that's a bug in `node-cache-manager`).

**Comment by simlu** [comment]
Ah! That makes a lot of sense. In that case should be documented that zero behaviour depends on underlying data store and should be avoided (ie prefer using 1ms)

**Comment by BryanDonovan** [comment]
Good point.. I could at least add that.  Might take a few days though.  Thanks!
