### ISSUE TITLE
Store engines aren't fully compatible with node-cache-manager 

### ISSUE THREAD

**Issue by lukechilds** [BryanDonovan/node-cache-manager#73]
From the readme it appears like the different store engines are drop in replacements for the default memory store. However they all seem to have varying degrees of support.

For example, I have developed my module using the default memory store and everything works well. If I use the Redis memory store it breaks my app as it doesn't support Promises on the get/set methods. I've submitted a PR to fix that but I've also noticed the `max` value in the options isn't respected when using Redis. On top of that, you can create multiple cache instances using the memory store and by default they will use a separate cache. Using the Redis store by default they all use the same DB and so will have cache collisions.

I've only tested the Redis store with my app but looking at the code for other store engines it looks like most will have similar issues.

These problems can all be worked around on the application side but this means that store engines aren't drop in replacements, they require changing application code. I think it would be better if all settings were defined in `node-cache-manager` and required to be respected by all store engines.

**Comment by BryanDonovan** [comment]
Yeah, it would be nice if the store engines had to respect all settings.  I'm not sure how the settings could be enforced from `node-cache-manager` though.

**Comment by lukechilds** [comment]
Maybe you could release a set of guidelines that a store engine should follow? Only store engines that follow these guidelines would then be linked to from the readme.

You could possibly also add integration tests for supported storage engines to the `node-cache-manager` repo.

**Comment by BryanDonovan** [comment]
I'm unsure how to proceed here.  The problem is that there will always be differences between cache stores, so only a few methods are guaranteed to be implemented (get, set, del, and maybe a ttl, but even ttl isn't guaranteed to exist).  E.g., I doubt all (or many) cache implementations have a `max` feature like the memory store.

**Comment by lukechilds** [comment]
So then in my opinion it should be up to the store engine to implement these features on top of the DB to provide a consistent interface.

Purge, ttl and max would be fairly trivial to implement manually for any DBs that don't support them natively.

**Comment by BryanDonovan** [comment]
In theory you could use MySQL as a cache store, which would not have an easy way to use a `ttl` (unless things have changed since I last used MySQL).  But that's a bit of a contrived example I guess. 

Maybe implementing the integration tests like you suggested would be a good first step.  Then we can see how compliant the various engines are.  I haven't thought through how to go about writing the integration tests in a way that makes it easy to test the other stores.  Any ideas there?

**Comment by lukechilds** [comment]
Re the MySQL ttl, this could be implemented in the store engine. For example, have an "expired" timestamp column in the table and check the key is still valid before returning it.

For integration tests, I would recommend using the exact same tests you test your memory implementation with.

**Comment by BryanDonovan** [comment]
Good idea.  I'll try to figure something out when I get some time, which I don't have much of these days..
